<Project>
  <PropertyGroup>
    <!-- Version is extracted from the first versioned section heading in release-notes.txt -->
    <Version>$([System.Text.RegularExpressions.Regex]::Match($([System.IO.File]::ReadAllText(`$(MSBuildThisFileDirectory)release-notes.txt`)), `(?m)^(\d+\.\d+\.\d+)`).Groups.get_Item(1).Value)</Version>
  </PropertyGroup>
</Project>
